version: "3.7"
services:
  #
  # book Microservice
  # 
  book-ms:
    build:
      context: ./book
    container_name: book-ms
    ports:
      - "8120:8120"
    depends_on:
      - mongodb_db

  #
  # customer Microservice
  # 
  customer-ms:
    build:
      context: ./customer
    container_name: customer-ms
    ports:
      - "8125:8125"
    depends_on:
      - mongodb_db

  mongodb_db:
    image: mongo:latest
    container_name: book-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: book_db
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  #
  # borrowing Microservice
  #
  borrowing-ms:
    build:
      context: ./borrowing
    container_name: borrowing-ms
    ports:
      - "8123:8123"
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:latest
    container_name: borrowing-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./borrowing/dbinit.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  #
  # Notification
  #
  notification-ms:
    build:
      context: ./notifications
    container_name: notification-ms
    ports:
      - "8124:8124"
    depends_on:
      - kafka

  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      zk_id: "1"

  kafka:
    image: bitnami/kafka
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      ALLOW_PLAINTEXT_LISTENER: "yes"

  


volumes:
 mongodb_data: {}
 postgres_data: {}
